spring:
  application:
    name: blog-springboot
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456
    url: jdbc:mysql://localhost:3306/blog_springboot
    username: elysia
  jwt:
    admin-secret-key: elysiaAdmin
    # 设置jwt过期时间
    admin-ttl: 86400
    # 设置前端传递过来的令牌名称
    admin-token-name: elysiaAdminToken
    # 设置jwt签名加密时使用的秘钥
    user-secret-key: elysiaUser
    # 设置jwt过期时间
    user-ttl: 86400
    # 设置前端传递过来的令牌名称
    user-token-name: elysiaUserToken
  data:
    redis:
      host: localhost
      port: 6379
aliyun:
  oss:
    endpoint: oss-cn-guangzhou.aliyuncs.com
    accessKeyId: ${ALIBABA_ACCESS_KEY_ID}
    accessKeySecret: ${ALIBABA_ACCESS_KEY_SECRET}
    bucketName: elysia-blog